#!/usr/bin/env node
import { writeFile, access } from "fs/promises"
import { constants } from "fs"
import * as opaque from "@serenity-kit/opaque"
import { generateKeyPair } from "jose"

function toBase64Url(buf) {
  return Buffer.from(buf).toString("base64").replace(/\+/g, "-").replace(/\//g, "_").replace(/=+$/, "")
}

async function fileExists(path) {
  try {
    await access(path, constants.F_OK)
    return true
  } catch {
    return false
  }
}

async function main() {
  const out = ".env"
  const force = process.argv.includes("--force")

  if ((await fileExists(out)) && !force) {
    console.error(`Refusing to overwrite existing file ${out}. Pass --force to overwrite.`)
    process.exit(1)
  }

  const { publicKey: pub, privateKey: priv } = await generateKeyPair("EdDSA", { extractable: true })
  const keyId = crypto.randomUUID()

  const privDer = await crypto.subtle.exportKey("pkcs8", priv)
  const pubDer = await crypto.subtle.exportKey("spki", pub)

  const privateB64 = toBase64Url(privDer)
  const publicB64 = toBase64Url(pubDer)

  const opaqueSecret = opaque.server.createSetup()

  const content = `# Generated by scripts/generate-keys.mjs
OPAQUE_SERVER_SETUP=${opaqueSecret}
POSTGRES_CONNECTION_STRING=postgres://postgres:postgres@localhost:5432/postgres
S3_ENDPOINT=http://localhost:9000
S3_ACCESS_KEY=minioadmin
S3_SECRET_KEY=minioadmin
S3_BUCKET_NAME=pathhub
S3_PUBLIC_BUCKET_NAME=pathhub-public
SIGNATURE_PRIVATE_KEY=${privateB64}
SIGNATURE_PUBLIC_KEY=${publicB64}
SIGNATURE_KEY_ID=${keyId}
`

  await writeFile(out, content, { encoding: "utf8", mode: 0o600 })

  console.log(`Wrote ${out}`)
  console.log("Private key (base64url):", privateB64)
  console.log("Public key  (base64url):", publicB64)
  console.log("OPAQUE secret        :", opaqueSecret)
}

main().catch((err) => {
  console.error(err)
  process.exit(1)
})
